---
title: "Ressources"
output: html_document
---

# **Graphical representation for multidimensional analyses**

ggade4 (see R package PBmisc)


# **Importation of pyrosequencing data with R and Python**

Tex document



# **R package [mgmtstp27](https://github.com/badozor/mgmtstp27)**

 * Documentation of R package mgmtstp27: [mgmtstp27](https://github.com/badozor/mgmtstp27/blob/master/trunk/Rdoc/mgmtstp27.pdf)
 
 * Introduction to R package mgmtstp27 (version 0.1, in preparation): [intromgmtstp27.pdf](https://github.com/badozor/mgmtstp27/blob/master/trunk/Rdoc/intromgmtstp27.pdf)
 
 * Effect of normalization on the prediction of DNA methylation status of MGMT promoter: example with HM-450K Infinium data from TCGA and the R package mgmtstp27 (version 0.1, in preparation): [docmgmtstp27.pdf](https://github.com/badozor/mgmtstp27/blob/master/trunk/Rdoc/docmgmtstp27.pdf)
 
 * Prediction of the DNA methylation of MGMT with raw data (format IDAT) from HM-27k (version 0.1, in preparation): [MgmtPredTCGA.pdf](https://github.com/badozor/mgmtstp27/blob/master/trunk/Rdoc/MgmtPredTCGA.pdf)
 

# **efitools (version 1.2)**

 * Bady, P., D. Pont, M. Logez & J. Veslot (2009). Improvement and spatial extension of the European Fish Index Deliverable 4.1 : Report on the modelling of reference conditions and on the sensitivity of candidate metrics to anthropogenic pressures. Deliverable 4.2: Report on the final development and validation of the new European Fish Index and method. 6th Framework Programme Priority FP6-2005-SSP-5-A. N° 0044096. Final Report, 179pp. DOI: 10.13140/RG.2.2.35757.67042, [document](https://www.researchgate.net/publication/375449574_Bady_P_D_Pont_M_Logez_J_Veslot_2009_Improvement_and_spatial_extension_of_the_European_Fish_Index_Deliverable_41_Report_on_the_modelling_of_reference_conditions_and_on_the_sensitivity_of_candidate_metr) and [software](https://www.researchgate.net/publication/376679683_efitools-12rar)
 

 
